/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.adesso.backend.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-02T11:27:47.656Z")

@Api(value = "deleteNote", description = "the deleteNote API")
public interface DeleteNoteApi {

    @ApiOperation(value = "Notiz löschen", nickname = "deleteNote", notes = "Löscht existierenden Notiz. Falls dieser nicht existiert wird ein Fehler geworfen (HTTP 409)", tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Notiz geloescht"),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 409, message = "Notiz existiert nicht") })
    @RequestMapping(value = "/deleteNote",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<String> deleteNote(@ApiParam(value = "ID des zu löschende Notiz"  )  @Valid @RequestBody String id);

}
