/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.adesso.backend.api;

import de.adesso.backend.model.Note;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-02T11:27:47.656Z")

@Api(value = "updateNote", description = "the updateNote API")
public interface UpdateNoteApi {

    @ApiOperation(value = "Notiz bearbeiten", nickname = "updateNote", notes = "Bearbeitet existierende Notiz. Falls dieser nicht existiert wird ein Fehler geworfen (HTTP 409)", tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Notiz bearbeitet"),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 409, message = "Notiz existiert nicht") })
    @RequestMapping(value = "/updateNote",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Note> updateNote(@ApiParam(value = "Bearbeitete Notiz"  )  @Valid @RequestBody Note note);

}
