/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.adesso.backend.api;

import de.adesso.backend.model.TerminTyp;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-02T11:27:47.656Z")

@Api(value = "updateTerminTyp", description = "the updateTerminTyp API")
public interface UpdateTerminTypApi {

    @ApiOperation(value = "Termin bearbeiten", nickname = "updateTerminTyp", notes = "Bearbeitet existierenden Termin. Falls dieser nicht existiert wird ein Fehler geworfen (HTTP 409)", tags={ "developers", })
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "TerminTyp bearbeitet"),
            @ApiResponse(code = 400, message = "invalid input, object invalid"),
            @ApiResponse(code = 409, message = "TerminTyp existiert nicht") })
    @RequestMapping(value = "/updateTerminTyp",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    ResponseEntity<TerminTyp[]> updateTerminTyp(@ApiParam(value = "Bearbeiteter TerminTyp"  )  @Valid @RequestBody TerminTyp[] terminTyp);

}
