/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.eventure.backend.api;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-31T18:36:00.556Z")

@Api(value = "deleteEmail", description = "the deleteEmail API")
public interface DeleteEmailApi {

    @ApiOperation(value = "Email löschen", nickname = "deleteEmail", notes = "Setzt eine Email auf inaktiv. Löschen ist Persistenzgründen nicht sinnvoll. Falls diese nicht existiert wird ein Fehler geworfen (HTTP 409)", tags={ "admin", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Email"),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 409, message = "Prüfung existiert nicht") })
    @RequestMapping(value = "/deleteEmail",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> deleteEmail(@ApiParam(value = "ID der zu löschenden Email"  )  @Valid @RequestBody Long id);

}
