/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.eventure.backend.api;

import de.eventure.backend.model.Ergebnis;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-31T18:36:00.556Z")

@Api(value = "updateErgebnis", description = "the updateErgebnis API")
public interface UpdateErgebnisApi {

    @ApiOperation(value = "Bearbeitet Prüfung", nickname = "updateErgebnis", notes = "", tags={ "alle", })
    @ApiResponses(value = {
        @ApiResponse(code = 201, message = "Ergebnis bearbeitet"),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 409, message = "an existing item already exists") })
    @RequestMapping(value = "/updateErgebnis",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Ergebnis> updateErgebnis(@ApiParam(value = "Ergebnis, die bearbeitet wird") @Valid @RequestBody Ergebnis ergebnis);

}
